### ISSUE TITLE
graphs not included in the component package

### ISSUE THREAD

**Issue by djdeath** [noflo/noflo-adapters#5]
Graphs are not included in the component distribution of the package, which leaves the runtime throwing errors when listing components.
I believe you need to "compile" those graphs into their json form to be embedded correctly.
Pretty much like this : 
https://github.com/djdeath/noflo-clutter/tree/master/graphs

**Comment by bergie** [comment]
We're now using WebPack with grunt-noflo-browser, so these work fine with fbp-loader
